service: aml-backend


provider:
  name: aws
  runtime: nodejs18.x
  stage: staging
  region: eu-west-1
  environment:
    REPORT_SETTINGS_TABLE_NAME: ${self:custom.reportSettingsTableName}
  
custom:
  reportSettingsTableName: report-settings-${self:provider.stage}

plugins:
  - serverless-iam-roles-per-function

functions:
  getReportSettings:
    handler: ./src/api/get-report-settings.handler
    name: get-report-settings
    memorySize: 128 
    timeout: 10
    events:
      - http:
          path: /report-settings/{id}
          method: GET
    iamRoleStatements:
      - Effect: "Allow"
        Action: 
          - "dynamodb:GetItem"
          - "dynamodb:Scan"
        Resource: !GetAtt ReportSettingsTable.Arn
  
  createReportSettings:
    handler: ./src/api/create-report-settings.handler
    name: create-report-settings
    memorySize: 128 
    timeout: 10
    events:
      - http:
          path: /report-settings
          method: POST
    iamRoleStatements:
      - Effect: "Allow"
        Action: 
          - "dynamodb:PutItem"
        Resource: !GetAtt ReportSettingsTable.Arn

resources:
  Resources:
    ReportSettingsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.reportSettingsTableName}
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5